from fastapi import APIRouter, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.schemas.answer_question import AnswerQuestionRequest, AnswerQuestionResponse
from app.schemas.document import (
    DocumentCreate,
    DocumentResponse,
)
from app.schemas.summarization import SummarizeRequest, SummarizeResponse
from app.services.answer_question_service import AnswerQuestionService, get_answer_question_service
from app.services.document import create_document, get_all_documents
from app.services.summarization_service import SummarizationService, get_summarization_service

router = APIRouter()


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@router.get("/documents", response_model=list[int])
async def get_documents(db: AsyncSession = Depends(get_db)) -> list[int]:
    docs = await get_all_documents(db)
    return [doc.id for doc in docs]


@router.post("/documents", response_model=DocumentResponse, status_code=status.HTTP_201_CREATED)
async def post_document(
    payload: DocumentCreate,
    db: AsyncSession = Depends(get_db),
) -> DocumentResponse:
    doc = await create_document(db, title=payload.title, content=payload.content)
    return DocumentResponse.model_validate(doc)


@router.post("/summarize_note", response_model=SummarizeResponse)
async def summarize_note(
    payload: SummarizeRequest,
    service: SummarizationService = Depends(get_summarization_service),
) -> SummarizeResponse:
    """Summarize a medical document using LLM.

    This endpoint accepts medical note text and returns a concise summary
    generated by a language model via Pydantic AI Gateway.

    Args:
        payload: Request containing the medical note content to summarize

    Returns:
        JSON response with the summary and metadata

    Raises:
        HTTPException 400: If the content is empty or invalid
        HTTPException 500: If the LLM API call fails for other reasons
        HTTPException 503: If the LLM API is temporarily unavailable (rate limits, timeouts)

    Example:
        POST /summarize_note
        {"content": "Patient presents with acute bronchitis..."}

        Response:
        {
            "summary": "Patient diagnosed with acute bronchitis...",
        }
    """
    summary = await service.summarize(payload.content)
    return SummarizeResponse(summary=summary)


@router.post("/answer_question", response_model=AnswerQuestionResponse)
async def answer_question(
    payload: AnswerQuestionRequest,
    service: AnswerQuestionService = Depends(get_answer_question_service),
) -> AnswerQuestionResponse:
    answer = await service.answer_question(payload.question)
    return AnswerQuestionResponse(answer=answer)
